routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/{order?}', 'HomeController@index')->name('home');

Route::resource('/articles', 'ArticlesController');

Route::post('upload_image', 'ArticlesController@uploadImage')->name('articles.upload_image');

Route::resource('/comments', 'CommentsController');

Route::resource('/categories', 'CategoriesController');

Route::get('/wiki/{category}', 'CategoriesController@articles')->name('wiki.index');

Route::post('/wikis/{wiki}/set', 'WikisController@set')->name('wikis.set');

Route::resource('/wikis', 'WikisController', ['only' => ['index', 'create', 'store', 'show']]);

// 创建一个版本
Route::get('/wikis/{wiki}/create', 'WikiRevisionsController@create')
    ->name('wiki.revisions.create');

Route::post('/wikis/{wiki}', 'WikiRevisionsController@store')
    ->name('wiki.revisions.store');

Route::get('/wikis/{wiki}/edit/{revision}', 'WikiRevisionsController@edit')
    ->name('wiki.revisions.edit');

Route::put('/wikis/{wiki}/edit/{revision}', 'WikiRevisionsController@update')
    ->name('wiki.revisions.update');

Route::get('/wikis/{wiki}/{revision}', 'WikiRevisionsController@show')
    ->name('wiki.revisions.show');

Route::get('relations', 'RelationController@index')
    ->name('relations.index');

Route::post('relations/{relation}', 'RelationController@toggleRelation')
    ->name('relations.toggle');

Route::resource('/users', 'UsersController');

Route::get('/revisions/{revision}', 'WikiRevisionsController@show')->name('revisions.show');

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Contracts\Commentable;

class Comment extends Model
{
    const COMMENTABLES = [
        Wiki::class,
        User::class,
    ];

    protected $fillable = [
        'commentable_id', 'commentable_type', 'user_id', 'banned_at', 'cache',
    ];

    protected $dates = [
        'banned_at',
    ];

    protected $with = [
        'user', 'content',
    ];

    protected $casts = [
        'id' => 'int',
        'user_id' => 'int',
        'cache' => 'object',
    ];

    protected $appends = [
        'has_up_voted', 'has_down_voted', 'up_voters', 'down_voters', 'created_at_timeago', 'updated_at_timeago',
    ];

    protected static function boot()
    {
        parent::boot();

        static::creating(function ($comment) {
            if(!$comment->user_id) {
                $comment->user_id = auth()->id();
            }
        });

        $saveContent = function ($comment) {
            if (request()->routeIs('comments.*') && request()->has('content')) {
                $data = ['body' => request()->input('content', [])];
                $comment->content()->updateOrCreate(['contentable_id' => $comment->id], $data);
                $comment->loadMissing('content');
            }
        };

        static::updated($saveContent);
        static::created($saveContent);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function commentable()
    {
        return $this->morphTo();
    }

    public function content()
    {
        return $this->morphOne(Content::class, 'contentable');
    }

    public function scopeValid($query)
    {
        $query->whereHas('user', function ($q) {
            $q->whereNotNull('activated_at')->whereNull('banned_at');
        });
    }

    public static function isCommentable($target)
    {
        if (\is_object($target)) {
            return $target instanceof Commentable;
        }

        $ref = new \ReflectionClass($target);

        return $ref->isSubclassOf(Commentable::class);
    }

    public function getHasUpVotedAttribute()
    {
        return $this->isUpvotedBy(auth()->user());
    }

    public function getHasDownVotedAttribute()
    {
        return $this->isDownvotedBy(auth()->user());
    }

    public function getUpVotersAttribute()
    {
        return $this->upvoters()->count();
    }

    public function getDownVotersAttribute()
    {
        return $this->downvoters()->count();
    }
}

app/Http/Controllers/CommentsController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Http\Requests\CommentRequest;
use App\Comment;
class CommentsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CommentRequest $request)
    {
        // $this->authorize('create', Comment::class);



        if (!Comment::isCommentable($request->get('commentable_type'))) {
            return back()->withErrors(['content' => '非法请求']);
        }

        $comment = Comment::create($request->all());

        return back()->with('success', '成功发布一条评论');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/comments/_comment.blade.php
@if (count($comments) > 0)
    @foreach($comments as $comment)
        <div id="comment-{{ $comment->id }}" name="comment-{{ $comment->id }}" class="border-bottom box-body py-2">
            <div class="user-media d-flex">
                <a href="#" class="">
                    <img src="{{ $comment->user->avatar }}" alt="{{ $comment->user->name }}" class="avatar-40">
                </a>
                <div class="ml-2">
                    <div><a href="#" class="">
                            <h6 class="mb-0 text-16 d-inline-block text-black-50 text-14">{{ $comment->user->name }}</h6>
                            <a href="#" class="text-muted text-12 ml-1">{{ $comment->user->name }}</a></a>
                    </div>
                    <small><a href="#comment-{{ $comment->id }}"
                              class="text-gray-70">{{ $comment->created_at->diffForHumans() }}</a></small>
                </div>
                <div class="text-16 text-gray-60 ml-auto d-flex align-items-center">
                    <div class="mx-1 cursor-pointer d-flex">
                        <button class="btn btn-icon btn-light text-gray-60">
                            <span class="mdi mdi-thumb-up"></span>
                        </button>
                        <span class="ml-1 align-self-center">0</span>
                    </div>
                </div>
            </div>
            <section class="comment-content text-gray-40 pt-2">
                <p>{!! $comment->content->body !!}</p>
            </section>
        </div>
    @endforeach
    {!! $comments->render() !!}
    @else
    @include('common._no_data', ['show' => '还没有人评论~'])
@endif

resources/views/comments/_create_form.blade.php
<div class="box mb-3">
    @auth
    <form method="POST" action="{{ route('comments.store') }}#comments">
        @csrf
        <input type="hidden" name="commentable_type" value="{{ get_class($wiki) }}"/>
        <input type="hidden" name="commentable_id" value="{{ $wiki->id }}"/>
        <div class="d-flex align-items-center w-100">
            <img src="{{ Auth::user()->avatar }}" class="avatar-40"/>
            <div class="text-18 text-muted ml-2 w-100">
                                            <textarea class="form-control" name="content"
                                                      placeholder="撰写评论..."></textarea>
            </div>
        </div>
        <div class="d-flex justify-content-between mt-2">
            @if ($errors->has('content'))
                <div class="flash-message ml-4">
                    <p class="alert alert-danger mb-0 ml-1 p-1">
                        {{ $errors->first('content') }}
                    </p>
                </div>
            @else
                <div class="flash-message ml-4">
                    <p class="alert alert-info mb-0 ml-1 p-1">
                        请不要发表不友好的评论
                    </p>
                </div>
            @endif
            <button type="submit" class="btn btn-primary">提交</button>
        </div>
    </form>
    @endauth
    @guest
        <a href="{{ route('login') }}">登录</a> 后可发表评论
    @endguest
</div>