routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/{order?}', 'HomeController@index')->name('home');

Route::resource('/articles', 'ArticlesController');

Route::post('upload_image', 'ArticlesController@uploadImage')->name('articles.upload_image');

Route::resource('/comments', 'CommentsController');

Route::resource('/categories', 'CategoriesController');

Route::get('/wiki/{category}', 'CategoriesController@articles')->name('wiki.index');

Route::post('/wikis/{wiki}/set', 'WikisController@set')->name('wikis.set');

Route::resource('/wikis', 'WikisController', ['only' => ['index', 'create', 'store', 'show']]);

// 创建一个版本
Route::get('/wikis/{wiki}/create', 'WikiRevisionsController@create')
    ->name('wiki.revisions.create');

Route::post('/wikis/{wiki}', 'WikiRevisionsController@store')
    ->name('wiki.revisions.store');

Route::get('/wikis/{wiki}/edit/{revision}', 'WikiRevisionsController@edit')
    ->name('wiki.revisions.edit');

Route::put('/wikis/{wiki}/edit/{revision}', 'WikiRevisionsController@update')
    ->name('wiki.revisions.update');

Route::get('/wikis/{wiki}/{revision}', 'WikiRevisionsController@show')
    ->name('wiki.revisions.show');

Route::get('relations', 'RelationController@index')
    ->name('relations.index');

Route::post('relations/{relation}', 'RelationController@toggleRelation')
    ->name('relations.toggle');

Route::resource('/users', 'UsersController');

Route::get('/revisions/{revision}', 'WikiRevisionsController@show')->name('revisions.show');

app/Wiki.php
<?php

namespace App;

use App\Contracts\Commentable;
use Overtrue\LaravelFollow\Traits\CanBeFavorited;
use Overtrue\LaravelFollow\Traits\CanBeLiked;
use Overtrue\LaravelFollow\Traits\CanBeSubscribed;
use Illuminate\Database\Eloquent\SoftDeletes;

class Wiki extends Model implements Commentable
{
    use SoftDeletes, CanBeSubscribed, CanBeFavorited, CanBeLiked;
    protected $fillable = ['title', 'founder_id', 'excellent_at',
        'pinned_at', 'frozen_at', 'banned_at', 'published_at', 'activated_at', 'cache',
        'cache->views_count', 'cache->comments_count', 'cache->likes_count', 'cache->subscriptions_count',
        'cache->last_reply_user_id', 'cache->last_reply_user_name', 'cache->last_edit_user_name', 'cache->last_edit_user_id'];

    protected $with = [
        'founder',
    ];

    protected $casts = [
        'id' => 'int',
        'user_id' => 'int',
        'is_excellent' => 'bool',
        'cache' => 'array',
    ];

    protected $dates = [
        'excellent_at', 'pinned_at', 'frozen_at', 'banned_at', 'published_at',
    ];

    const CACHE_FIELDS = [
        'views_count' => 0,
        'comments_count' => 0,
        'likes_count' => 0,
        'subscriptions_count' => 0,
        'last_reply_user_id' => 0,
        'last_reply_user_name' => null,
        'last_edit_user_name' => null,
        'last_edit_user_id' => 0,
    ];

    public function categories()
    {
        return $this->belongsToMany(Category::class, 'category_wiki');
    }

    public function getVersionAttribute()
    {
        return $this->revisions()->first();
    }

    public function scopeRecent($query)
    {
        return $query->whereNull('banned_at')->with('founder')->orderBy('pinned_at', 'desc')->orderBy('excellent_at', 'desc')->orderBy('created_at', 'desc');
    }

    public function comments()
    {
        return $this->morphMany(Comment::class, 'commentable');
    }

    public function founder()
    {
        return $this->belongsTo(User::class);
    }

    // 关联分类 / 标签


    public function afterCommentCreated(Comment $lastComment)
    {
        // $lastComment->user->subscribe($this);
    }

    public function revisions()
    {
        return $this->hasMany(WikiRevision::class)->where('type', '=', 'version')->orderBy('created_at', 'desc')->orderBy('id', 'desc');
    }

    public function attachments()
    {
        return $this->hasMany(Attachment::class, 'uploaded_to')->orderBy('order', 'asc');
    }

    public function getCurrentRevision()
    {
        return $this->revisions()->first();
    }

    // 更新统计字段
    public function refreshCache()
    {
        $lastComment = $this->comments()->latest()->first();

        $this->update(['cache' => \array_merge(self::CACHE_FIELDS, [
            'views_count' => $this->cache['views_count'],
            'comments_count' => $this->comments()->count(),
            'likes_count' => $this->likers()->count(),
            'subscriptions_count' => $this->subscribers()->count(),
            'last_reply_user_id' => $lastComment ? $lastComment->user->id : 0,
            'last_reply_user_name' => $lastComment ? $lastComment->user->name : '',
        ])]);
    }


}

app/Http/Controllers/WikisController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\WikiCreateRequest;
use App\WikiRevision;
use Illuminate\Http\Request;
use App\Wiki;
use App\Category;
use Auth;
use Mews\Purifier\Facades\Purifier;
use App\Services\WikiActivityLogService;
class WikisController extends Controller
{
    protected $activityLog;
    public function __construct(WikiActivityLogService $activityLog)
    {
        $this->middleware('auth')->except('index', 'show');
        $this->activityLog = $activityLog;
    }

    public function index(Wiki $wiki)
    {
        $wikis = $wiki->paginate(10);
        return view('wikis.index', compact('wikis'));
    }

    public function show(Wiki $wiki)
    {
        if ($revision = $wiki->getCurrentRevision())
        {
            $revision->is_default_version = true;
        }
        $wiki->loadMissing('likers', 'subscribers');
        $comments = $wiki->comments()->paginate(10);
        $wiki_logs = $this->activityLog->getLogs($wiki);

        return view('wikis.show', compact('wiki', 'revision', 'comments', 'wiki_logs'));
    }
    public function create()
    {
        return view('wikis.create');
    }

    public function store(Wiki $wiki, WikiCreateRequest $request)
    {
        $wiki->fill($request->all());
        $wiki->founder_id = Auth::id();
        $wiki->save();
        $this->activityLog->created($wiki, Auth::user());
        return redirect()->route('wikis.show', $wiki->id)->with('success', '词条创建成功');
    }

    public function edit(Wiki $wiki, WikiRevision $version = null)
    {
        if ($wiki->frozen_at) {
            return redirect()->back()->with('warning', '该词条已被锁定，禁止编辑');
        }
        $categories = Category::with('children')->root()->get();
        $revision = $wiki->getCurrentRevision();
        return view('wikis.create_and_edit', compact('wiki', 'categories', 'revision', 'version'));
    }

    public function update(Wiki $wiki, Request $request, WikiRevision $revision = null)
    {
        $isChange = $this->checkChange($wiki, $request, $revision);
        if ( ! $isChange) {
            return redirect()->back()->with('warning', '未做任何修改！');

        } else if($revision) {
            $revision->fill($request->all());
            $revision->user_id = auth()->id;
            $revision->save();
            return redirect()->route('wikis.show', ['wiki' => $wiki->id, 'version' => $revision->id])->with('success', '成功修改过一个版本');
        }else {
            $revision = $this->createNewRevision($wiki);
            $revision->fill($request->all());
            $revision->save();
            return redirect()->route('wikis.show', ['wiki' => $wiki->id])->with('success', '成功提交一个版本');
        }
    }

    public function set(Wiki $wiki, Request $request)
    {
        $type = $request->type;
        if (in_array($type, ['excellent', 'pinned', 'frozen', 'banned'])) {
            if(!$wiki->getAttribute($type . '_at')) {
                $wiki->update([
                    $type . '_at' => now()
                ]);
            } else {
                $wiki->update([
                    $type . '_at' => null
                ]);
            }
        }
        return redirect()->back();
    }

    protected function checkChange($wiki, $request, $version = null)
    {
        if (!$version) {
            $version = $wiki->getCurrentRevision();
        }
        $oldCategories = $version->categories->pluck('id')->toArray();
        $requestCategory = explode(',', $request->category);
        $newCategories = collect($requestCategory)->map(function ($i, $key) {
            return (int) $i;
        })->toArray();
        $titleChange = $wiki->title !== $request->title;
        $contentChange = $version->content->body !== Purifier::clean($request->body);
        $categoryChange = $oldCategories !== $newCategories;
        if (!$titleChange && !$contentChange && !$categoryChange) {
            return false;
        }
        return true;
    }

    protected function createNewRevision(Wiki $wiki)
    {
        return $revision = $wiki->revisions()->create([
                'user_id' => Auth::id(),
        ]);
    }
}

resources/views/wikis/_logs.blade.php
@if(count($wiki_logs) > 0)
<div class="box my-3">
    <ul class="list-group list-group-flush">
        @foreach($wiki_logs as $log)
            <li class="list-group-item d-md-flex d-block align-items-center justify-content-between">
                <div class="d-flex align-items-center w-70">
                    <a href="#" class="mr-2">
                        <img src="{{ $log->causer->avatar }}" alt="{{ $log->causer->name }}" class="avatar-30" />
                    </a>
                    @if($log->log_name === 'wiki.created')

                    <div class="text-gray-50">
                        {{ $log->description }} {{ $log->subject->title }}
                    </div>
                    @elseif($log->log_name === 'wiki.revision.created')
                    <div class="text-gray-50">
                        {{ $log->description }} <a href="{{ route('wiki.revisions.show', ['wiki' => $wiki->id, 'revision' => $log->getExtraProperty('revision')['id']]) }}">
                            {{ $log->getExtraProperty('revision')['changelog'] ?? $log->subject->title }}</a>
                    </div>
                    @elseif($log->log_name === 'wiki.categories.change')
                        <div class="text-gray-50">
                            {{ $log->description }}
                            @foreach($log->getExtraProperty('categories') as $category)
                            <a href="{{ route('wiki.index', $category['slug']) }}">{{ $category['title'] }}</a>
                            @endforeach
                        </div>
                    @endif
                </div>
                <div class="ml-auto d-flex align-items-center justify-content-md-end">
                    <div class="ml-1 text-gray-60">
                        <small>{{ $log->created_at->diffForHumans() }}</small>
                    </div>
                </div>
            </li>
        @endforeach
    </ul>
</div>
@endif

resources/views/wikis/_wikis_list.blade.php
@if(count($wikis) > 0)
<ul class="list-group list-group-flush">
    @foreach($wikis as $wiki)
        <li class="list-group-item d-md-flex d-block align-items-center justify-content-between cursor-pointer">
            <div class="d-flex align-items-center w-70">
                <a href="#" class="mr-2">
                    <img src="{{ $wiki->founder->avatar }}" alt="{{ $wiki->founder->name }}" class="avatar-30">
                </a>
                <div class="text-gray-50">
                    @if ($wiki->pinned_at)
                        <span class="badge badge-danger">置顶</span>
                    @endif
                    @if($wiki->excellent_at)
                        <span class="badge badge-success">精华</span>
                    @endif
                    @if($wiki->frozen_at)
                        <span class="badge badge-secondary">锁定</span>
                    @endif
                    @if($wiki->banned_at)
                        <span class="badge badge-secondary">封禁</span>
                    @endif
                    <a href="{{ route('wikis.show', $wiki->id) }}">{{ $wiki->title }}</a>
                </div>
            </div>
            <div class="ml-auto d-flex align-items-center justify-content-md-end">
                <div class="text-gray-60 d-flex justify-content-between align-items-center">
                                        <span class="p-1">
                                            <i class="mdi mdi-heart" aria-hidden="true"></i> {{ $wiki->cache['likes_count'] }}
                                        </span>
                    <span class="p-1">
                                            <i class="mdi mdi-comment" aria-hidden="true"></i> {{ $wiki->cache['comments_count'] }}
                                        </span>
                    <span class="p-1">
                                            <i class="mdi mdi-eye" aria-hidden="true"></i> {{ $wiki->cache['views_count'] }}
                                        </span>
                </div>
                <div class="ml-1 text-gray-60">
                    <small>{{ $wiki->updated_at->diffForHumans() }}</small>
                </div>
            </div>

        </li>
    @endforeach
</ul>
{{ $wikis->appends(Request::except('page'))->render() }}
@else
    @include('common._no_data')
@endif

resources/views/wikis/create.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="page-threads-show">
            <div class="row mt-md-3">
                <div class="col-md-9 m-auto">
                    <form method="post" action="{{ route('wikis.store') }}">
                            @csrf
                            <div class="input-group">
                                <input name="title" class="form-control form-control-lg" type="text"
                                       placeholder="输入名称"
                                       value="{{ old('title', '') }}"/>
                            </div>
                            @if ($errors->has('title'))
                                <div class="flash-message mt-2">
                                    <p class="alert alert-danger">
                                        {{ $errors->first('title') }}
                                    </p>
                                </div>
                            @endif
                            <div class="mt-md-3 mt-1">
                                <button type="submit" class="btn btn-primary">提交</button>
                            </div>
                        </form>
                </div>
            </div>
        </div>
    </div>
@stop

resources/views/wikis/create_and_edit.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="page-threads-show">
            <div class="row mt-md-3">
                <div class="col-md-9 m-auto">
                    <wiki-create-edit inline-template>
                        @if (isset($version))
                            <form method="post" action="{{ route('wikis.update', ['wiki' => $wiki->id, 'reversion' => $version->id]) }}">
                                @method('put')
                                <input type="hidden" name="id" value="{{ $wiki->id }}" />
                                @elseif($wiki->id)
                                    <form method="post" action="{{ route('wikis.update', ['wiki' => $wiki->id]) }}">
                                    @method('put')
                                    <input type="hidden" name="id" value="{{ $wiki->id }}" />
                                @else
                                    <form method="post" action="{{ route('wikis.store') }}">
                                        @endif
                                        @csrf
                                        <input type="hidden" name="type" v-model="createType">
                                        <div class="input-group">
                                            <input name="title" class="form-control form-control-lg" type="text"
                                                   placeholder="输入标题"
                                                   value="{{ old('title', $wiki->title ?? '') }}"/>
                                        </div>
                                        @if ($errors->has('title'))
                                            <div class="flash-message mt-2">
                                                <p class="alert alert-danger">
                                                    {{ $errors->first('title') }}
                                                </p>
                                            </div>
                                        @endif

                                        <div class="editor mt-3">
                                            <textarea name="content" class="form-control"
                                                      id="editor">{{ old('content', $revision ? $revision->content->body : '') }}</textarea>
                                        </div>
                                        @if ($errors->has('body'))
                                            <div class="flash-message mt-2">
                                                <p class="alert alert-danger">
                                                    {{ $errors->first('body') }}
                                                </p>
                                            </div>
                                        @endif
                                        <div class="mt-md-3 mt-1">
                                            <span class="text-muted">选择标签</span>
                                            <div class="message" v-if="categoryMsg">
                                                <div class="alert alert-warning mb-0">@{{ categoryMsg }}</div>
                                            </div>
                                        </div>
                                        <div class="mt-1 d-flex flex-wrap">
                                            @if(count($categories) > 0)
                                                <template v-for="(category, index) in categories">
                                                <div>
                                                    <div class="text-muted">@{{ category.title }}</div>
                                                    <button
                                                    style="margin: .25rem;"
                                                    @click.stop.prevent="checkCategory(index, i, cate.id)"
                                                    :class="{'btn': true, 'btn-primary': cate.check, 'btn-light': !cate.check}"
                                                    v-for="(cate, i) in category.children"
                                                >@{{ cate.title }}
                                                </button>
                                                </div>

                                                </template>
                                            @else
                                                <div class="m-1">还没有标签</div>
                                            @endif
                                        </div>
                                        <div class="mt-1 d-flex flex-wrap">
                                            <div class="mr-2" style="margin: 1px;">
                                                <button class="btn btn-secondary"
                                                        @click.stop.prevent="showAddCategory">@{{ addCate ? '取消' : '添加标签' }}
                                                </button>
                                            </div>
                                            <div class="input-group w-75" v-if="addCate">
                                                <div class="input-group-prepend">
                                                    <button class="btn btn-outline-secondary dropdown-toggle"
                                                            type="button" data-toggle="dropdown" aria-haspopup="true"
                                                            aria-expanded="false">@{{ addCategoryParentTitle }}
                                                    </button>
                                                    <div class="dropdown-menu">
                                                        <a class="dropdown-item" href="javascript:;"
                                                           @click="selectAddCategoryParentId(category.id, category.title)"
                                                           v-for="category in categories"
                                                           v-if="category.category_id <= 0">
                                                            @{{ category.title }}
                                                        </a>
                                                    </div>
                                                </div>
                                                <input type="text" class="form-control"
                                                       aria-label="Text input with dropdown button" v-model="addCategoryTitle" placeholder="输入标题">
                                                <div class="input-group-append">
                                                    <button v-if="addCate" class="btn btn-secondary"
                                                            @click.stop.prevent="addCategory">添加
                                                    </button>
                                                </div>
                                            </div>
                                        </div>
                                        @if ($errors->has('category'))
                                            <div class="flash-message mt-2">
                                                <p class="alert alert-danger">
                                                    {{ $errors->first('category') }}
                                                </p>
                                            </div>
                                        @endif
                                        <input type="hidden" name="category" :value="selectCategories">

                                        <div class="mt-md-3 mt-1">
                                            <button type="submit" class="btn btn-primary">发 布</button>
                                            <button type="submit" class="btn btn-secondary ml-1" @click="createType = 'draft'">保存为草稿</button>
                                        </div>
                                    </form>
                    </wiki-create-edit>
                </div>
            </div>
        </div>
    </div>
@stop
@prepend('scripts')
    <script>
        var categories = @json($categories);
        @php
        if($revision && $revision->categories) {
            $s = $revision->categories->pluck('id')->toArray();
        } else {
            $s = explode(',', old('category'));
        }
        foreach($s as $k=>$v) {
            $s[$k] = (integer) $v;
        }
        @endphp

        var selectCategories = @json($s);
        console.log(selectCategories);
    </script>
@endprepend
@section('styles')
    <link rel="stylesheet" type="text/css" href="{{ asset('css/simditor.css') }}">
@stop
@section('scripts')
    <script type="text/javascript" src="{{ asset('js/module.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/hotkeys.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/uploader.js') }}"></script>
    <script type="text/javascript" src="{{ asset('js/simditor.js') }}"></script>
    <script>
        console.log(categories);
        $(document).ready(function () {
            var editor = new Simditor({
                textarea: $('#editor'),
                toolbar: [
                    'title',
                    'bold',
                    'italic',
                    'underline',
                    'strikethrough',
                    'fontScale',
                    'color',
                    'ol',
                    'ul',
                    'blockquote',
                    'table',
                    'link',
                    'image',
                    'hr',
                    'indent',
                    'outdent',
                    'alignment'
                ],
                upload: {
                    url: '{{ route('articles.upload_image') }}',
                    params: {
                        _token: '{{ csrf_token() }}'
                    },
                    fileKey: 'upload_file',
                    connectionCount: 3,
                    leaveConfirm: '文件上传中，关闭此页面将取消上传。'
                },
                pasteImage: true,
            });
        });
    </script>
@stop

resources/views/wikis/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="container my-3">
        <div class="row">
            <div class="col-md-9">
                <div class="box box-flush">
                    <div class="box-body">
                        <ul class="nav nav-pills">
                            <li class="nav-item"><a href="/?hot" class="nav-link active">活跃</a></li>
                            <li class="nav-item"><a href="/?j" class="nav-link">精选</a></li>
                            <li class="nav-item"><a href="/?no_reply" class="nav-link">零回复</a></li>
                            <li class="nav-item"><a href="/?new" class="nav-link">最新发布</a></li>
                        </ul>

                    </div>
                    <div class="threads-items mb-2">
                        @include('wikis._wikis_list')
                    </div>
                </div>
            </div>
            <div class="col-md-3"></div>
        </div>
    </div>
@stop