routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Auth::routes();

Route::get('/{order?}', 'HomeController@index')->name('home');

Route::resource('/articles', 'ArticlesController');

Route::post('upload_image', 'ArticlesController@uploadImage')->name('articles.upload_image');

Route::resource('/comments', 'CommentsController');

Route::resource('/categories', 'CategoriesController');

Route::get('/wiki/{category}', 'CategoriesController@articles')->name('wiki.index');

Route::post('/wikis/{wiki}/set', 'WikisController@set')->name('wikis.set');

Route::resource('/wikis', 'WikisController', ['only' => ['index', 'create', 'store', 'show']]);

// 创建一个版本
Route::get('/wikis/{wiki}/create', 'WikiRevisionsController@create')
    ->name('wiki.revisions.create');

Route::post('/wikis/{wiki}', 'WikiRevisionsController@store')
    ->name('wiki.revisions.store');

Route::get('/wikis/{wiki}/edit/{revision}', 'WikiRevisionsController@edit')
    ->name('wiki.revisions.edit');

Route::put('/wikis/{wiki}/edit/{revision}', 'WikiRevisionsController@update')
    ->name('wiki.revisions.update');

Route::get('/wikis/{wiki}/{revision}', 'WikiRevisionsController@show')
    ->name('wiki.revisions.show');

Route::get('relations', 'RelationController@index')
    ->name('relations.index');

Route::post('relations/{relation}', 'RelationController@toggleRelation')
    ->name('relations.toggle');

Route::resource('/users', 'UsersController');

Route::get('/revisions/{revision}', 'WikiRevisionsController@show')->name('revisions.show');

resources/views/layouts/_category_item.blade.php
<!-- 如果当前类目有 children 字段并且 children 字段不为空 -->
@foreach($categoryTree as $category)
@if(isset($category['children']) && count($category['children']) > 0)
  <li class="nav-item">
    <div class="btn-group">
        <a href="#" id="categoryDropdown-{{ $category['id'] }}" class="dropdown-item dropdown-toggle" data-toggle="dropdown">{{ $category['title'] }}</a>
        <div class="dropdown-menu dropdown-menu-left" aria-labelledby="categoryDropdown-{{ $category['id'] }}">
          <!-- 遍历当前类目的子类目，递归调用自己这个模板 -->
          <a href="{{ route('wiki.index', $category['slug']) }}" class="dropdown-item">{{ $category['title'] }}</a>
          @foreach($category['children'] as $childCategory)
            <a href="{{ route('wiki.index', $childCategory['slug']) }}" class="dropdown-item">{{ $childCategory['title'] }}</a>
          @endforeach
        </div>
    </div>
  </li>
@endif
@endforeach

resources/views/layouts/_footer.blade.php
<div class="container-fluid" style="min-height: 188px;">

</div>

resources/views/layouts/_header.blade.php
<nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm py-1 shadow-6">
    <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
            {{ config('app.name', 'Laravel') }}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav flex-row align-items-center justify-content-center py-sm-2 py-md-0 mx-auto">

                <li class="nav-item active">
                    <a href="/" class="nav-link">首页</a>
                </li>
                <li class="nav-item">
                    <a href="/" class="nav-link">动态</a>
                </li>
                @include('layouts._category_item')
            </ul>
            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-md-auto flex-row d-md-flex align-items-center justify-content-around">
                <!-- Authentication Links -->
                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                    </li>
                    @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                    @endif
                @else
                    <li class="nav-item">
                        <a href="{{ route('wikis.create') }}"
                           class="text-20 btn btn-icon btn-transparent btn-light active">
                            <i class="mdi mdi-plus"
                               aria-hidden="true"></i>
                        </a>
                    </li>
                    <li class="nav-item">
                        <div class="btn-group">
                            <a id="navbarDropdown" class="dropdown-toggle cursor-pointer" href="#" role="button"
                               data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                <img src="{{ Auth::user()->avatar }}" class="avatar-40 mr-2"/>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <div class="dropdown-item">
                                    <a href="/users/{{ Auth::user()->id }}" class="">
                                        <div class="text-16 text-gray-30">{{ Auth::user()->name }}</div>
                                        <div>{{ '@' . Auth::user()->name }}</div>
                                    </a>
                                </div>
                                <div class="dropdown-divider"></div>
                                <a href="/user/profile" class="dropdown-item">个人中心</a>
                                <a href="/user/profile" class="dropdown-item">编辑资料</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="{{ route('logout') }}"
                                   onclick="event.preventDefault();
                                                         document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST"
                                      style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ mix('css/app.css') }}" rel="stylesheet">
    @yield('styles')
    <!-- 初始化变量 -->
    @stack('scripts')
</head>
<body>
    <div id="app">
        @include('layouts._header')
        @include('shared._messages')
        <main class="">
            @yield('content')
        </main>
    </div>
    <!-- Scripts -->
    @include('layouts._footer')
    <script src="{{ mix('js/app.js') }}"></script>
    @yield('scripts')
    @if (app()->isLocal())
        @include('sudosu::user-selector')
    @endif
</body>
</html>